### ISSUE TITLE
Questions about benefits for SP2016 patching and Zero Downtime Patching scenarios

### ISSUE THREAD

**Issue by cloudgreen** [Nauplius/SharePoint-Patch-Script#15]
Hi Trevor!

First, thanks a lot for all your contributions to the SP community, I don't know how many times your input has helped me! :)

I have a few questions that might be a little more like discussion points:

1. For SP2016, are there any "unique technical gains" of using this PS module over manual installation, or is it more of just increased convenience for downloading & installation?

I'm not trying to marginalize your script by any means, I'm just curious about specifics. :) Like, with Russ Maxwell's 2013 script there was a tangible benefit of much shorter binary installation time, thanks to service stops and such, but as we know those are [no longer needed in SP2016](https://github.com/Nauplius/SharePoint-Patch-Script/issues/9). (The Search pausing is feature seems very convenient indeed, and it's part of the next question...)

2. I am currently investigating Zero Downtime Patching for SP2016, but when doing that, I'm thinking I should _not_ pause any Search Service Applications, as it would kind of ruin the "zero downtime" concept. :) (Microsoft's [ZDP page actually mentions keeping search and crawls alive but further down they also suggest pausing crawls](https://docs.microsoft.com/en-us/SharePoint/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps).) How do you see your module in a SP2016 ZDP scenario? Is it redundant (pun not intended)? :)

Sorry if it's a bit abstract, thanks for any thoughts!

**Comment by tseward** [comment]
For 2016+, there are not *technical* gains per se (that is reducing patching time <5 hours), but there is still the recommendation of pausing search (you don't necessarily want a crawler running while updating a server for performance and availability reasons).

In the latest script I also moved the functionality (sans a zip file extractor for some very old 2010 patches) of my C# PoSh modules into the script, such as downloading patches using the script from Microsoft.

Pausing the SSA doesn't interrupt your ability to perform a search, only the ability to perform crawls, run/collect analytics, and indexing (https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/suspend-spenterprisesearchserviceapplication?view=sharepoint-ps#examples).

Because of this, I don't see pausing the SSA as conflicting with ZDP as search is still available to end users.

**Comment by cloudgreen** [comment]
Thanks for your detailed response and sorry for my late reply!

Ah, great info about suspending/pausing a SSA - I had misunderstood it and believed it made search unavailable for end users. I've performed it several times in the past, but never realized search was actually still available... :)

Grateful for your reflection about the technical gains as well. I will definitely investigate using your module for pausing the SSA. We have in fact 4 separate SSA:s, and I see your module supports multiple so that should be good! :)

Thanks again!
