### ISSUE TITLE
How to execute Operating Mode

### ISSUE THREAD

**Issue by rolandon** [Nauplius/SharePoint-Patch-Script#3]
Awesome script. Can you tell how to run the script in operating mode? do i run the script from the APP01 server or from a remote server? Where should the ARSPPM.psm1 be located?

**Comment by tseward** [comment]
SharePointPatchScript.psm1 must be run locally on the server you're patching. This differs from ARSPPM.psm1 which allows remote patching of a farm; the script can run on your local client machine, for example.

**Comment by rolandon** [comment]
Thanks,
For some reason the script get stuck trying to stop search and if search manually get stop the services never gets restarted. I am running a 2 server farm Sharepoint 2016.

Who is be possible to add a email report of the farm status after each sever gets patched?

**Comment by tseward** [comment]
I've seen a few cases where Search does not stop or pause successfully. Usually this is due to an issue present on the farm that otherwise would not surface in normal operation. I'd suggest diving into the ULS logs to see if you can identify why. Given the script is using standard SharePoint commands, there is nothing script-specific that would cause Search to fail to stop/pause.
